param(
    [string]$Repository = "xdCloudy/minecraft-native-intelligence"
)

$ErrorActionPreference = "Stop"

$labels = @(
    @{Name="area:minecraft"; Color="0E8A16"; Description="Minecraft integration and mechanics"},
    @{Name="area:agent-runtime"; Color="1D76DB"; Description="Agent lifecycle, identity, and scheduling"},
    @{Name="area:memory"; Color="5319E7"; Description="Persistent memory and consolidation"},
    @{Name="area:learning"; Color="7057FF"; Description="Policies, continual learning, and adaptation"},
    @{Name="area:language"; Color="D93F0B"; Description="Grounded communication"},
    @{Name="area:multi-agent"; Color="006B75"; Description="Multi-agent interaction and scaling"},
    @{Name="area:training"; Color="B60205"; Description="Training pipelines and model lifecycle"},
    @{Name="area:data"; Color="FBCA04"; Description="Telemetry, datasets, licensing, and privacy"},
    @{Name="area:infra"; Color="C5DEF5"; Description="Developer infrastructure and operations"},
    @{Name="area:docs"; Color="0075CA"; Description="Documentation"},
    @{Name="area:evaluation"; Color="D4C5F9"; Description="Evaluation and benchmarks"},
    @{Name="type:feature"; Color="A2EEEF"; Description="New engineering capability"},
    @{Name="type:research"; Color="BFD4F2"; Description="Decision-oriented research"},
    @{Name="type:experiment"; Color="F9D0C4"; Description="Reproducible experiment"},
    @{Name="type:bug"; Color="D73A4A"; Description="Incorrect behaviour"},
    @{Name="type:refactor"; Color="EDEDED"; Description="Internal restructuring"},
    @{Name="type:docs"; Color="0E8A16"; Description="Documentation change"},
    @{Name="type:test"; Color="BFDADC"; Description="Test or verification work"},
    @{Name="priority:critical"; Color="B60205"; Description="Blocks the programme or a safety invariant"},
    @{Name="priority:high"; Color="D93F0B"; Description="Important near-term work"},
    @{Name="priority:medium"; Color="FBCA04"; Description="Planned work"},
    @{Name="priority:low"; Color="C2E0C6"; Description="Useful, not time-sensitive"},
    @{Name="status:blocked"; Color="000000"; Description="Cannot proceed until a dependency changes"},
    @{Name="status:needs-design"; Color="FEF2C0"; Description="Needs design or evidence before implementation"},
    @{Name="status:ready"; Color="0E8A16"; Description="Scoped and ready to start"},
    @{Name="good first issue"; Color="7057FF"; Description="Suitable for a new contributor"},
    @{Name="help wanted"; Color="008672"; Description="Maintainers welcome focused help"}
)

$milestones = @(
    "v0.1 — Project Foundation",
    "v0.2 — Minecraft Native Interface",
    "v0.3 — Agent Runtime",
    "v0.4 — Memory",
    "v0.5 — Behaviour Baseline",
    "v0.6 — Language Grounding",
    "v0.7 — Autonomous Behaviour",
    "v0.8 — Lifelong Learning",
    "v0.9 — Multi-Agent Intelligence",
    "v0.10 — Scaling & Simulation",
    "v0.11 — Integrated Research Prototype",
    "v1.0 — Native Intelligence Research Release"
)

function New-IssueSpec($title, $milestone, $labels, $context, $goal, $scope, $deliverables, $acceptance, $dependencies = "None known.", $questions = "") {
    return [ordered]@{Title=$title; Milestone=$milestone; Labels=$labels; Context=$context; Goal=$goal; Scope=$scope; Deliverables=$deliverables; Acceptance=$acceptance; Dependencies=$dependencies; Questions=$questions}
}

$issues = @(
    New-IssueSpec "Research Minecraft mod loader and version support" "v0.1 — Project Foundation" @("area:minecraft","type:research","priority:critical","status:ready") "The native interface needs a stable, maintainable integration point, but Fabric, NeoForge, server plugins, and custom harnesses differ in observability, lifecycle, licensing, and version support." "Recommend a platform/version strategy without implementing the agent." "Compare active candidates against client/server access, headless operation, mapping stability, testability, distribution, and community support." "Decision matrix, minimal spike plan, risks, and proposed ADR." "Primary sources are cited; at least three credible options are compared; recommendation and falsifiers are explicit." "Blocks observation/action implementation." "Which platform exposes required state legally and testably? Which versions maximize research reproducibility without creating permanent lock-in?"
    New-IssueSpec "Define Java and research-runtime process boundaries" "v0.1 — Project Foundation" @("area:infra","area:minecraft","type:research","priority:high","status:ready") "Minecraft integration likely runs on the JVM while model research may use another ecosystem; coupling choices affect latency and replaceability." "Specify candidate in-process and out-of-process boundaries." "Compare IPC transports, schema tooling, failure isolation, batching, deployment, and debugging without selecting a research language by preference." "Interface options, latency test plan, recommendation criteria, and ADR draft." "At least two boundaries are prototyped or costed; failure and versioning behaviour is described." "Minecraft platform research." "What latency and throughput budget is required? Which boundary best preserves modularity and recovery?"
    New-IssueSpec "Specify structured observation schema v0" "v0.2 — Minecraft Native Interface" @("area:minecraft","type:feature","priority:critical","status:needs-design") "Models and runtimes need a versioned contract for legitimate local state and events." "Publish a minimal extensible schema for observations." "Cover identity/world references, time, pose, needs, inventory, local blocks, sensed entities, events, masks, frames, and schema negotiation." "Schema, examples, compatibility rules, and contract tests." "Every field has units/source/visibility semantics; unknown and absent differ; old/new version tests pass." "Mod platform and field-of-view rules."
    New-IssueSpec "Specify native action schema v0" "v0.2 — Minecraft Native Interface" @("area:minecraft","type:feature","priority:critical","status:needs-design") "A policy needs typed actions with timing and outcomes, not commands or direct mutations." "Define the minimal action request/outcome contract." "Movement, look, jump, attack, mine, place, interact, inventory, craft, equip, eat, and chat; include cancellation and rejection." "Schema, examples, state machine, and compatibility tests." "Actions cannot bypass mechanics; requests correlate with accepted/rejected/completed outcomes; invalid inputs fail closed." "Mod platform and legal-action validator."
    New-IssueSpec "Design entity representation and identity semantics" "v0.2 — Minecraft Native Interface" @("area:minecraft","type:research","priority:high","status:needs-design") "Entities change type, visibility, state, and instance identity across observations." "Choose a representation that supports learning without leaking server-global truth." "Compare typed features, sets/graphs/tokens, stable sensed identifiers, occlusion, re-identification, and uncertainty." "Representation proposal, edge cases, prototype encoding, and tests." "Handles spawn/despawn, occlusion, similar entities, mounts/projectiles, and information loss explicitly." "Observation schema." "What identity continuity may an ordinary player infer? Which attributes are observed versus derived?"
    New-IssueSpec "Design local block and terrain representation" "v0.2 — Minecraft Native Interface" @("area:minecraft","type:research","priority:high","status:needs-design") "Voxel worlds are large, sparse, dynamic, and multi-scale." "Select candidate local geometry encodings for model experiments." "Compare dense voxels, sparse sets, octrees, graphs, egocentric slices, chunk features, and change events." "Benchmarked prototype encoders and recommendation criteria." "Measures bandwidth, latency, reconstruction, spatial tasks, and hidden-state compliance on varied terrain." "Observation schema and information-access rules." "Which encoding preserves affordances at acceptable cost? How are unloaded and remembered blocks distinguished?"
    New-IssueSpec "Define field-of-view and information-access rules" "v0.2 — Minecraft Native Interface" @("area:minecraft","area:evaluation","type:research","priority:critical","status:ready") "Native APIs can expose omniscient server state unavailable to ordinary players, invalidating results." "Specify enforceable partial-observability rules." "Visibility, ray/occlusion, distance, darkness, hearing, inventory/self state, chunk loading, recipes, chat, and operator exceptions." "Threat model, rule table, conformance scenarios, and unresolved questions." "Each observation field maps to a rule; tests detect hidden chunk/entity leaks; exceptions are explicit and disabled in baselines." "Minecraft platform research." "What counts as legitimately sensed? Where is ordinary-player equivalence technically ambiguous?"
    New-IssueSpec "Implement legal-action validation contract" "v0.2 — Minecraft Native Interface" @("area:minecraft","type:feature","priority:critical","status:needs-design") "Model requests may be malformed, impossible, too fast, or prohibited." "Create an authoritative validation layer that reports failures as observations." "Validate schemas, capability, reach, timing, inventory, cooldowns, permissions, and cancellation; Minecraft remains final authority." "Validator interface, error taxonomy, adversarial contract tests, and traces." "No tested request bypasses ordinary mechanics; rejection is deterministic and observable; fail-closed behaviour is documented." "Action schema and mod platform."
    New-IssueSpec "Design persistent agent identity record" "v0.3 — Agent Runtime" @("area:agent-runtime","type:feature","priority:critical","status:needs-design") "Every agent needs a stable identity independent of model process and session." "Define the identity root and ownership invariants." "Identifiers, world binding, creation metadata, lifecycle state, personal-state references, display policy, and schema version." "Schema, threat analysis, examples, and serialization tests." "Two agents cannot resolve to the same mutable state accidentally; IDs survive restart; clone/import semantics are explicit." "Persistence-store research."
    New-IssueSpec "Implement agent save/load lifecycle prototype" "v0.3 — Agent Runtime" @("area:agent-runtime","type:feature","priority:critical","status:needs-design") "Long-running lives require crash-safe persistence and version evolution." "Prototype create, pause, save, load, migrate, export, and delete flows." "Atomicity, interrupted writes, compatibility, world mismatch, backup, and administrative deletion." "Lifecycle API, reference storage adapter, migrations, and failure-injection tests." "Round-trip state is stable; partial writes recover; deletion/export are authorized and auditable." "Identity schema and storage decision."
    New-IssueSpec "Design multi-timescale cognition scheduler" "v0.3 — Agent Runtime" @("area:agent-runtime","area:multi-agent","type:research","priority:high","status:needs-design") "Reactive control, behaviour selection, planning, consolidation, and learning operate at different cadences." "Define scheduler contracts and priority/backpressure semantics." "Tick budgets, interrupts, deadlines, async work, stale results, fairness, safe idle, and observability." "Scheduler model, simulation, latency budgets, and ADR proposal." "Shows no global stall from one slow agent and defines stale-output handling for every loop." "Runtime process boundary." "Which work must be synchronous with ticks? How should distant/sleeping agents degrade?"
    New-IssueSpec "Define memory service abstraction" "v0.4 — Memory" @("area:memory","type:feature","priority:critical","status:needs-design") "Memory types need a shared boundary without forcing a database or retrieval method." "Specify versioned write/query/revise/forget/consolidate interfaces." "Ownership, provenance, confidence, time, evidence links, access control, transactions, and observability." "API schema, reference in-memory adapter, contract tests, and migration rules." "All four memory types fit without lossy generic blobs; cross-agent access fails; queries expose provenance." "Identity schema."
    New-IssueSpec "Prototype episodic memory" "v0.4 — Memory" @("area:memory","type:experiment","priority:high","status:needs-design") "Raw event streams are too large and poorly shaped for long-term recall." "Test episode segmentation, salience, compression, and retrieval." "Compare at least two segmentation/retrieval strategies on delayed Minecraft event questions and decisions." "Prototype, dataset/scenarios, metrics, raw results, and conclusion." "Reports recall/precision, storage, latency, time ordering, and causal behavioural utility over multiple seeds." "Memory service and telemetry schema." "Do learned or heuristic boundaries preserve decision-relevant events? What salience signal avoids novelty-only bias?"
    New-IssueSpec "Prototype semantic memory with evidence" "v0.4 — Memory" @("area:memory","type:experiment","priority:high","status:needs-design") "Agents need durable facts and beliefs that are not treated as unquestionable text." "Represent claims, confidence, evidence, sources, and revision." "Test facts learned from observation, chat, and consolidation, including stale and conflicting cases." "Prototype store/retriever, benchmark cases, metrics, and conclusion." "Every belief is source-linked; conflicting evidence remains inspectable; decisions reflect calibrated confidence." "Memory service and contradiction design." "Which belief representation supports revision and bounded retrieval? How should confidence combine across sources?"
    New-IssueSpec "Prototype spatial memory" "v0.4 — Memory" @("area:memory","area:minecraft","type:experiment","priority:high","status:needs-design") "Agents must remember places and routes while the world changes and chunks unload." "Compare spatial map/topology representations under partial observation." "Locations, landmarks, routes, structures, hazards, coordinate frames, uncertainty, and change detection." "Prototype representations, navigation scenarios, metrics, and recommendation." "Supports save/load and route retrieval; distinguishes observed/current/remembered; reports failures after world changes." "Observation schema and memory service." "Which representation enables multi-scale navigation at bounded storage? How should conflicting map evidence revise?"
    New-IssueSpec "Design procedural memory and skill representation" "v0.4 — Memory" @("area:memory","area:learning","type:research","priority:high","status:needs-design") "Reusable behaviour must persist without becoming arbitrary executable scripts that hide intelligence." "Evaluate representations for learned skills and their applicability conditions." "Policy fragments, latent skills/options, trajectories, symbolic summaries, success/failure models, composition, and versioning." "Comparison matrix, prototype plan, safety analysis, and ADR candidate." "Separates learned parameters from metadata; defines validation and transfer tests; arbitrary host execution is excluded." "Action schema and behaviour baseline." "What is the smallest safe, composable skill representation? How is applicability learned and falsified?"
    New-IssueSpec "Experiment with memory consolidation and forgetting" "v0.4 — Memory" @("area:memory","type:experiment","priority:medium","status:needs-design") "Unlimited raw memory is costly and retrieval degrades; destructive summaries can invent or erase evidence." "Test auditable consolidation, decay, and protected retention." "Episode-to-belief/skill summaries, importance, duplicate merging, decay, source links, rollback, and asynchronous scheduling." "Prototype jobs, longitudinal scenarios, metrics, and conclusion." "Measures information retention, hallucinated facts, storage/latency, rollback, and impact on later decisions." "Episodic and semantic prototypes." "When should memory consolidate or decay? Which records must remain immutable evidence?"
    New-IssueSpec "Handle contradictory knowledge and belief revision" "v0.4 — Memory" @("area:memory","type:experiment","priority:high","status:needs-design") "Players may be mistaken or deceptive and the world changes over time." "Build and test explicit contradiction and revision semantics." "Direct observation versus testimony, temporal validity, source reliability, retractions, unresolved alternatives, and confidence." "Scenario suite, algorithms, UI/trace examples, and results." "Agent does not blindly overwrite; competing claims and provenance are inspectable; temporal changes do not become logical contradictions." "Semantic memory prototype." "How should evidence strength, recency, and source history interact? When should the agent ask or re-observe?"
    New-IssueSpec "Research relationship representation" "v0.4 — Memory" @("area:memory","area:multi-agent","type:research","priority:medium","status:needs-design") "Relationships need persistent, evidence-grounded state without scripted labels or psychological overclaiming." "Propose representations and behavioural evaluations." "Interaction history, expectations, trust dimensions, commitments, reputation, uncertainty, privacy, and change over time." "Literature review, candidate schema, scenario plan, and risks." "Avoids single ungrounded friend/enemy score; state is per-agent and evidence-linked; evaluation tests behavioural consequences." "Identity and semantic/episodic memory." "Which dimensions are identifiable from interaction? How do private and shared reputations differ?"
    New-IssueSpec "Research experience-shaped personality representations" "v0.7 — Autonomous Behaviour" @("area:agent-runtime","area:learning","type:research","priority:medium","status:needs-design") "Prompted traits do not establish persistent behavioural personality." "Identify mechanisms that create measurable, experience-dependent decision tendencies." "Latent preferences, habit learning, value priors, stability/plasticity, observability, and cross-context evaluation." "Primary-source review, candidate mechanisms, experiment designs, and ethical limits." "At least two non-prompt mechanisms are compared; tests remove language output; divergence and stability metrics are defined." "Behaviour baseline and persistent memory." "What constitutes behavioural evidence of personality? How can experience change tendencies without identity collapse?"
    New-IssueSpec "Research intrinsic motivation signals" "v0.7 — Autonomous Behaviour" @("area:learning","type:research","priority:high","status:needs-design") "Autonomy requires activity selection beyond fixed external tasks, while novelty rewards can create pathological exploration." "Compare intrinsic signals and their failure modes in Minecraft." "Curiosity, competence progress, empowerment, homeostasis, social signals, novelty, boredom, and multi-objective arbitration." "Review, benchmark scenarios, candidate formulations, and safety constraints." "Includes noisy-TV, neglect, reward-hacking, cycling, and social manipulation tests; no signal is adopted without ablation." "Evaluation framework and behaviour baseline." "Which signals yield diverse useful behaviour without hardcoding projects? How do memory and habituation affect motivation?"
    New-IssueSpec "Prototype autonomous goal generation and revision" "v0.7 — Autonomous Behaviour" @("area:learning","area:agent-runtime","type:experiment","priority:high","status:needs-design") "Agents need to choose, pursue, abandon, resume, and reprioritize activities without constant instructions." "Test a goal lifecycle conditioned on needs, memory, personality, affordances, and social commitments." "Goal proposal, value/feasibility estimates, conflict resolution, planning hooks, progress, abandonment, and resumption." "Prototype, longitudinal scenarios, metrics, trace viewer output, and conclusion." "Produces diverse non-commanded activity; traces explain evidence; avoids impossible-goal loops; scripted goal content is disclosed." "Intrinsic-motivation research, memory, and behaviour baseline." "How are goal novelty and continuity balanced? When should a commitment override immediate reward?"
    New-IssueSpec "Research hierarchical control and policy decomposition" "v0.5 — Behaviour Baseline" @("area:learning","type:research","priority:high","status:needs-design") "Minecraft spans tick-level control and projects lasting days; one flat policy may be inefficient or brittle." "Compare hierarchy designs across reactive, behavioural, and deliberative timescales." "Options/skills, goal-conditioned policies, planners, interruptibility, credit assignment, and learned-versus-scripted boundaries." "Review, interface proposals, controlled experiments, and recommendation criteria." "At least two hierarchy approaches use the same native interface and benchmarks; latency and transfer are measured." "Action schema, scheduler, and evaluation framework." "Which abstractions can be learned and reused? How should high-level choices interrupt low-level control?"
    New-IssueSpec "Define imitation-learning dataset strategy" "v0.5 — Behaviour Baseline" @("area:data","area:training","type:research","priority:critical","status:needs-design") "A broad behavioural prior may need human or expert trajectories aligned to native observations and actions." "Design a lawful, representative, versioned data strategy." "Collection sources, consent, native instrumentation, coverage, quality, splits, scale, bias, retention, and pixel-to-native transfer." "Dataset requirements, collection protocol, cost ranges, risks, and go/no-go plan." "Provenance/licensing are explicit; coverage maps to target skills; leakage controls and deletion path are defined." "Telemetry format, observation/action schemas, licensing research." "How much native aligned data is necessary? Can existing pixel datasets transfer without compromising native grounding?"
    New-IssueSpec "Specify gameplay telemetry and dataset format" "v0.2 — Minecraft Native Interface" @("area:data","type:feature","priority:critical","status:needs-design") "Training and evaluation require aligned, replayable, provenance-rich trajectories." "Define a versioned telemetry container and manifest." "Observations, events, actions/outcomes, time, identities, world/version, traces, compression, checksums, redaction, and extensions." "Schema, small fixtures, reader contract, validation tool design, and privacy fields." "Round-trip preserves ordering and masks; corrupt/incompatible data fails clearly; provenance and consent metadata are required." "Observation/action schemas and data policy."
    New-IssueSpec "Research dataset licensing, consent, and privacy" "v0.1 — Project Foundation" @("area:data","type:research","priority:critical","status:ready") "Gameplay, video, chat, skins, worlds, and derived labels can have different rights and privacy constraints." "Produce a collection/use decision framework, not legal conclusions beyond evidence." "Minecraft EULA/policies, contributor consent, third-party datasets, chat/identifiers, retention/deletion, weights, and publication." "Source-backed matrix, consent template requirements, risk register, and review triggers." "Every proposed source has owner, license/terms, intended use, redistribution/training status, and unresolved legal questions." "None." "Which artifacts can be collected, trained on, and redistributed? What consent and deletion promises are technically supportable?"
    New-IssueSpec "Implement native behavioural-cloning baseline" "v0.5 — Behaviour Baseline" @("area:learning","area:training","type:experiment","priority:high","status:needs-design") "The project needs a reproducible learned baseline before evaluating more complex architectures." "Train and evaluate a minimal policy on native trajectories." "Fixed task subset, data loader, encoder/policy baseline, training recipe, checkpoints, and ablations against simple heuristics." "Reproducible code/config, licensed sample data, metrics, model card, and results." "Runs from a clean environment; reports held-out seeds, variance, latency, failures, and data/compute scale; no unsupported generality claims." "Dataset strategy, telemetry, native interface, and evaluation framework." "How much competence transfers across seeds and biomes? Which native features drive improvement?"
    New-IssueSpec "Build evaluation framework and scenario contract" "v0.1 — Project Foundation" @("area:evaluation","area:infra","type:feature","priority:critical","status:ready") "Comparisons need common scenario definitions, seeds, metrics, traces, and learned-versus-scripted accounting." "Specify a framework independent of one model or mod loader." "Scenario setup, capabilities, reset/replay, metrics, repetitions, timeouts, artifacts, baselines, and result schema." "Contract, example scenarios, runner spike, result manifest, and CI strategy." "Same experiment is reproducible; variance and failures are preserved; privileged information and scripts are declared." "Minecraft platform and process-boundary research."
    New-IssueSpec "Design benchmark taxonomy and anti-shortcut checks" "v0.5 — Behaviour Baseline" @("area:evaluation","type:research","priority:high","status:needs-design") "Fixed tasks can be memorized or solved using privileged signals and may not measure general intelligence." "Define a layered evaluation taxonomy and leakage tests." "Unit skills, compositional tasks, held-out worlds, perturbations, longitudinal autonomy, social interaction, and ecological metrics." "Benchmark specification, shortcut threat model, split strategy, and governance." "Each benchmark states construct, confounds, baselines, generalisation split, and failure interpretation." "Evaluation framework." "Which measures predict open-world competence? How can scripts, seed memorization, and hidden state be detected?"
    New-IssueSpec "Create navigation evaluation suite" "v0.5 — Behaviour Baseline" @("area:evaluation","area:minecraft","type:test","priority:high","status:needs-design") "Navigation spans locomotion, local avoidance, exploration, route recall, and changed terrain." "Create reproducible native navigation scenarios." "Short pathing, vertical terrain, hazards, partial maps, route memory, detours, and held-out seeds." "Scenario definitions, metrics, baselines, fixtures, and reporting." "Measures success, path/time cost, interventions, falls/damage, generalisation, and memory benefit across seeds." "Evaluation framework, observation/action schemas, spatial memory."
    New-IssueSpec "Create survival evaluation suite" "v0.5 — Behaviour Baseline" @("area:evaluation","area:minecraft","type:test","priority:high","status:needs-design") "Survival integrates perception, resource decisions, risk, time, and recovery." "Build staged scenarios without turning survival into a single reward." "Health/hunger, shelter, night, hazards, recovery, resource scarcity, and long episodes." "Scenarios, metrics, baselines, perturbations, and result schema." "Reports survival time and causal submetrics; cannot pass through cheats; held-out worlds and failure traces are included." "Evaluation framework and legal actions."
    New-IssueSpec "Create building evaluation suite" "v0.5 — Behaviour Baseline" @("area:evaluation","area:minecraft","type:test","priority:medium","status:needs-design") "Building quality includes intention, geometry, material planning, repair, and creativity, not one blueprint match." "Define quantitative and human-evaluable building tasks." "Blueprint execution, structural constraints, material acquisition, repair, free construction, and multi-session continuation." "Scenarios, geometric metrics, blinded rubric, inter-rater plan, and baselines." "Separates planning/acquisition/placement errors; reports rubric reliability; does not claim creativity from one metric." "Evaluation framework and behaviour baseline."
    New-IssueSpec "Create communication evaluation suite" "v0.6 — Language Grounding" @("area:evaluation","area:language","type:test","priority:high","status:needs-design") "Fluent chat can be ungrounded and causally irrelevant." "Measure reference, memory, learning, coordination, and belief revision through language." "Situated questions, ambiguous reference, teaching, delayed recall, false claims, clarification, joint tasks, and AI/human peers." "Scenarios, metrics, annotation guide, baselines, and privacy protocol." "Requires correct world evidence and later behaviour; scores unsupported fluency separately; inter-rater reliability is reported." "Language pathway, memory, and evaluation framework."
    New-IssueSpec "Prototype world-state-grounded language pathway" "v0.6 — Language Grounding" @("area:language","type:experiment","priority:high","status:needs-design") "Language must share representations with perception, memory, planning, and action rather than run as a detached chatbot." "Test architectures that condition communication on legitimate state and return grounded speech actions." "Context assembly or multimodal fusion, entity/place reference, memory citations, action consequences, and latency." "Prototype(s), ablations, grounded scenarios, metrics, and conclusion." "Removing world/memory inputs measurably harms grounded tasks; outputs cannot access hidden/external state; latency is reported." "Behaviour baseline, memory, and communication evaluation." "Which architecture yields causal grounding? How can answers cite internal evidence without exposing implementation concepts?"
    New-IssueSpec "Evaluate player-to-agent teaching and conversation" "v0.6 — Language Grounding" @("area:language","area:evaluation","type:experiment","priority:medium","status:needs-design") "An agent should learn durable, revisable knowledge from another player without blindly obeying or believing." "Test instruction, explanation, questions, correction, and delayed use." "Human-scripted and live protocols, claim provenance, ambiguity, false statements, consent, and later behavioural tests." "Protocol, scenarios, transcripts with privacy controls, metrics, and results." "Agent asks when needed, retains source-linked knowledge, revises against evidence, and applies learning after delay." "Semantic memory and grounded language pathway." "When should testimony update belief or action? How does relationship/source history affect confidence?"
    New-IssueSpec "Evaluate agent-to-agent grounded conversation" "v0.9 — Multi-Agent Intelligence" @("area:language","area:multi-agent","type:experiment","priority:high","status:needs-design") "AI peers should use the same channel as humans and communicate from separate partial observations." "Measure information sharing, teaching, coordination, and misunderstanding without privileged side channels." "Separate memories, asymmetric observations, chat-only coordination, bandwidth limits, misinformation, and joint tasks." "Scenarios, metrics, traces, ablations, and results." "No cross-agent state leakage; messages improve measurable joint outcomes; errors and emergent terminology are analysed." "Grounded language, multi-agent scheduler, and identity isolation." "Does communication carry grounded information beyond policy correlation? What conventions persist across sessions?"
    New-IssueSpec "Implement multi-agent scheduling prototype" "v0.9 — Multi-Agent Intelligence" @("area:multi-agent","area:agent-runtime","type:feature","priority:critical","status:needs-design") "Concurrent agents need fair cognition, action, persistence, and model access under load." "Build a scheduler using explicit budgets and isolation." "Priority classes, deadlines, batching hooks, backpressure, cancellation, sleeping agents, and metrics." "Prototype, load generator, fairness tests, failure injection, and operator controls." "One slow agent does not stall others; bounded queue/latency; identity context never crosses requests; degradation is observable." "Runtime scheduler design and batched inference contract."
    New-IssueSpec "Prototype batched shared-model inference" "v0.10 — Scaling & Simulation" @("area:multi-agent","area:infra","type:experiment","priority:high","status:needs-design") "Per-agent model copies do not scale, while batching can mix state or increase latency." "Measure dynamic batching with strict request/context ownership." "Batch keys, variable sequences, caches, priorities, cancellation, adapter selection, and failure isolation." "Serving prototype, benchmark harness, isolation tests, profiles, and results." "Reports throughput/latency/memory versus agent count; adversarial tests find no state/cache leakage; deadlines are enforced." "Model interface, scheduler, and selected baseline." "What batching policy preserves responsiveness? Can caches be safely reused per agent?"
    New-IssueSpec "Design sleeping and low-frequency cognition modes" "v0.10 — Scaling & Simulation" @("area:multi-agent","area:agent-runtime","type:research","priority:medium","status:needs-design") "Large populations cannot all deliberate at full rate, especially when sleeping, idle, distant, or unloaded." "Define fidelity levels that preserve causal world continuity." "Transition triggers, missed events, summaries, world simulation, wake-up, fairness, and exploit resistance." "Mode specification, simulation experiments, resource/quality curves, and risks." "No hidden information appears; consequential events are preserved; transitions are deterministic/auditable; quality tradeoff is measured." "Scheduler and simulation acceleration research." "Which cognition can pause safely? How are experiences summarized without fabricating perception?"
    New-IssueSpec "Research shared foundation model architecture" "v0.5 — Behaviour Baseline" @("area:learning","area:training","type:research","priority:critical","status:needs-design") "The core shared competence may combine world modelling, policy, planning, and language in many ways." "Compare plausible modular, unified, and hybrid architectures against project requirements." "Native modalities, timescales, memory interfaces, language, batching, trainability, interpretability, and compute." "Primary-source review, candidate diagrams, experiment matrix, and decision criteria." "Does not equate foundation model with LLM; includes at least three alternatives and staged falsification tests." "Schemas, behavioural baseline, and evaluation framework." "Which components benefit from shared representations? Which must remain separate for latency, safety, or adaptation?"
    New-IssueSpec "Research per-agent adapters and personal modules" "v0.8 — Lifelong Learning" @("area:learning","area:multi-agent","type:research","priority:medium","status:needs-design") "Agents may need parameter-level individuality without duplicating full models or forgetting shared competence." "Evaluate adapters, LoRA-like modules, skill heads, and memory-only controls." "Training cadence, routing, storage, batching, privacy, inheritance, rollback, and retention." "Review, prototype plan, cost model, threats, and acceptance metrics." "Includes memory-only baseline; quantifies per-agent memory/latency; defines lineage, isolation, and deletion semantics." "Shared-model architecture and continual-learning strategy." "When do personal parameters add value beyond memory? How can mixed-adapter batches remain isolated?"
    New-IssueSpec "Define continual-learning strategy and gates" "v0.8 — Lifelong Learning" @("area:learning","area:training","type:research","priority:critical","status:needs-design") "Online experience is non-IID and parameter updates can erase skills, encode private data, or destabilize behaviour." "Create a staged, reversible lifelong-learning policy." "Memory-only baseline, replay, regularisation, modular growth, adapters, offline windows, promotion, rollback, and privacy." "Evidence review, experiment matrix, checkpoint policy, stop criteria, and ADR proposal." "Old/new/generalisation/safety tests and resource budgets are predeclared; automatic promotion is excluded initially." "Behaviour baseline, memory, adapters research, and checkpoint handling." "Which updates happen per agent versus shared? What evidence is sufficient to promote or revert an update?"
    New-IssueSpec "Build catastrophic-forgetting regression suite" "v0.8 — Lifelong Learning" @("area:evaluation","area:learning","type:test","priority:critical","status:needs-design") "Average new-task reward can hide erased old skills, facts, language grounding, or constraints." "Create longitudinal retention and interference tests." "Sequential skills/worlds, delayed facts, routes, social knowledge, safety invariants, backward/forward transfer, and recovery." "Suite, metrics, reference curves, reporting format, and CI/offline tiers." "Measures before/after/retention over time and multiple seeds; detects both parameter and memory interference; raw results are retained." "Baseline models, memory prototypes, and continual-learning plan."
    New-IssueSpec "Prototype offline consolidation and replay" "v0.8 — Lifelong Learning" @("area:learning","area:training","type:experiment","priority:high","status:needs-design") "Slower offline windows may adapt safely, but replay selection and synthetic data can bias or leak experience." "Compare offline update strategies under fixed compute and retention budgets." "Replay buffers, sampling, memory summaries, adapter versus shared updates, validation, promotion, and rollback." "Reproducible runs, checkpoints, learning/forgetting curves, privacy review, and conclusion." "Beats memory-only or fixed-model baselines on declared metrics without exceeding forgetting/safety thresholds; negative results are published." "Continual-learning gates and forgetting suite." "Which experiences merit replay? Do summaries preserve causal training signal?"
    New-IssueSpec "Specify model checkpoint and version lifecycle" "v0.5 — Behaviour Baseline" @("area:training","area:infra","type:feature","priority:high","status:needs-design") "Shared and personal model artifacts require lineage, compatibility, promotion, and rollback." "Define immutable artifact identity and lifecycle." "Hashes, parentage, code/data/config versions, schema compatibility, signatures, storage, retention, adapters, promotion, and rollback." "Manifest schema, CLI/API contract, example lineage, and integrity tests." "Every loaded artifact is verified and compatible; ancestry is queryable; rollback is tested; personal deletion semantics are documented." "Training/reproducibility framework."
    New-IssueSpec "Build reproducible experiment framework" "v0.1 — Project Foundation" @("area:infra","area:training","type:feature","priority:critical","status:ready") "Research results need repeatable configuration and inspectable artifacts across changing stacks." "Define a minimal stack-neutral experiment contract and initial runner." "Configuration, seeds, environment capture, commands, logging, artifact manifests, status, comparison, and failure preservation." "Specification, reference runner spike, sample experiment, and CI smoke test." "A clean machine can reproduce the sample; config and code revision are immutable; failures retain diagnostics." "Evaluation framework; may begin with a language-neutral schema."
    New-IssueSpec "Research accelerated Minecraft simulation" "v0.10 — Scaling & Simulation" @("area:minecraft","area:infra","type:research","priority:high","status:needs-design") "Training and evaluation at normal real-time tick speed may be prohibitive." "Compare safe acceleration strategies and their fidelity limits." "Headless servers, tick acceleration, parallel worlds, simplified simulators, snapshot/reset, determinism, mechanics drift, and licensing." "Benchmarks, fidelity tests, resource model, and recommendation." "Compares throughput and behavioural divergence; identifies mechanics that cannot be approximated; no hidden-state access enters policy inputs." "Native interface and deterministic environment research." "How fast can Minecraft run reproducibly? Which abstractions preserve transfer to ordinary worlds?"
    New-IssueSpec "Prototype deterministic and replayable environment support" "v0.10 — Scaling & Simulation" @("area:minecraft","area:evaluation","type:experiment","priority:high","status:needs-design") "Nondeterministic ticks, mobs, networking, and mods make failures difficult to reproduce." "Measure achievable determinism and implement trace-driven replay where exact determinism fails." "Seeds, tick ordering, randomness, snapshots, external events, action traces, hashes, and divergence detection." "Prototype, determinism matrix, replay fixtures, divergence reports, and limitations." "Repeated runs quantify divergence; replay detects first mismatch; unsupported sources are documented rather than hidden." "Platform selection, telemetry, and evaluation framework." "Which randomness can be controlled? When is statistical reproducibility more honest than exact replay?"
    New-IssueSpec "Design observability and trace schema" "v0.3 — Agent Runtime" @("area:infra","area:agent-runtime","type:feature","priority:high","status:needs-design") "Long-horizon behaviour is impossible to debug without correlated decisions, memory access, actions, and outcomes." "Define privacy-aware structured traces across system boundaries." "Correlation IDs, timings, model/checkpoint, memory reads/writes, action lifecycle, errors, redaction, sampling, and retention." "Schema, examples, viewer requirements, redaction tests, and metrics." "One behaviour can be reconstructed without exposing secrets/private chat by default; cross-agent mix-ups are detectable." "Observation/action, memory, and runtime schemas."
    New-IssueSpec "Establish performance profiling harness" "v0.10 — Scaling & Simulation" @("area:infra","area:multi-agent","type:test","priority:medium","status:needs-design") "Scaling decisions need comparable CPU/GPU/memory/network/tick measurements." "Build repeatable profiles from one agent to target populations." "Synthetic and Minecraft loads, warmup, percentiles, queueing, storage, inference, tick health, and artifact output." "Harness, baseline scenarios, metrics dashboard format, and runbook." "Reports hardware/software and confidence intervals; isolates subsystem costs; detects regressions at agreed thresholds." "Scheduler, model serving, observability."
    New-IssueSpec "Define test architecture and quality gates" "v0.1 — Project Foundation" @("area:infra","type:test","priority:high","status:ready","good first issue") "The future mixed-stack repository needs consistent test layers without premature framework commitment." "Specify unit, contract, integration, simulation, statistical, security, and longitudinal test tiers." "Ownership, fixtures, seeds, flake policy, runtime budgets, artifact retention, and required PR/nightly gates." "Testing strategy, example contract fixtures, naming conventions, and adoption checklist." "Every proposed subsystem maps to test tiers; nondeterminism policy is explicit; fast versus expensive gates are separated." "Architecture documents."
    New-IssueSpec "Expand CI from documentation to stack-aware checks" "v0.1 — Project Foundation" @("area:infra","type:feature","priority:medium","status:ready","good first issue") "Current CI validates documentation only; future code needs reproducible checks as stacks are selected." "Add a minimal extensible CI layout without selecting technologies prematurely." "Path-filtered jobs, formatting/lint/type/test hooks, dependency caching, artifact retention, concurrency, permissions, and security hygiene." "Workflow design and implementation for any accepted tooling present at that time." "Least-privilege permissions; pinned/reviewed actions; local equivalents documented; required checks finish within target PR budget." "Test architecture and first accepted implementation stack."
    New-IssueSpec "Audit and improve contributor documentation" "v0.1 — Project Foundation" @("area:docs","type:docs","priority:low","status:ready","good first issue","help wanted") "New contributors must navigate a large research programme without reinterpreting the goal." "User-test documentation links, terminology, issue workflow, and first-task guidance." "README journey, local links, glossary consistency, issue/PR templates, research reproducibility, and onboarding gaps." "Link report, targeted edits, and reviewer checklist." "All local links pass; five representative questions can be answered from docs; no duplicated authoritative text is introduced." "Initial repository bootstrap."
    New-IssueSpec "Design integrated prototype readiness review" "v0.11 — Integrated Research Prototype" @("area:evaluation","area:docs","type:research","priority:medium","status:blocked") "Subsystem success does not guarantee a coherent persistent world; integration can hide degraded grounding or identity failures." "Define entry criteria and an end-to-end validation protocol for v0.11." "Interface compatibility, capability matrix, persistence, autonomy, language, multi-agent load, observability, safety, recovery, and limitations." "Readiness checklist, scenario portfolio, evidence bundle format, and release blockers." "Criteria trace to earlier milestone evidence; no single demo can pass; known failures and scripted components are mandatory disclosures." "Blocked by v0.10 completion." "Which subsystem guarantees compose? What new failure modes appear only in long-running integration?"
    New-IssueSpec "Define v1.0 research release evidence and artifact policy" "v1.0 — Native Intelligence Research Release" @("area:docs","area:evaluation","type:research","priority:medium","status:blocked") "A research-platform release needs stable interfaces and honest claims, not an implied promise of human-level intelligence." "Specify release criteria, reproducibility bundle, supported configurations, and claim review." "API/schema stability, docs, licenses, model/data cards, benchmarks, known limitations, security, migration, archival artifacts, and citation." "Release policy, evidence checklist, support matrix, and claim-language guide." "Every public claim maps to reproducible evidence; artifacts have licenses/checksums; limitations and non-goals remain prominent." "Blocked by integrated prototype evidence." "What stability is necessary for research users? Which results can be independently reproduced and maintained?"
)

foreach ($label in $labels) {
    gh label create $label.Name --repo $Repository --color $label.Color --description $label.Description --force | Out-Null
}

$existingMilestones = gh api "repos/$Repository/milestones?state=all&per_page=100" | ConvertFrom-Json
foreach ($title in $milestones) {
    if (-not ($existingMilestones | Where-Object title -eq $title)) {
        gh api --method POST "repos/$Repository/milestones" -f title=$title -f description="See ROADMAP.md for outcome, dependencies, and exit gate." | Out-Null
    }
}

$existingIssues = gh issue list --repo $Repository --state all --limit 200 --json title | ConvertFrom-Json
foreach ($issue in $issues) {
    if ($existingIssues | Where-Object title -eq $issue.Title) {
        Write-Host "exists: $($issue.Title)"
        continue
    }

    $researchSection = if ($issue.Questions) { "`n## Research questions`n`n$($issue.Questions)`n" } else { "" }
    $body = @"
## Problem / context

$($issue.Context)

## Goal

$($issue.Goal)

## Scope

$($issue.Scope)
$researchSection
## Likely deliverables

$($issue.Deliverables)

## Acceptance criteria

$($issue.Acceptance)

## Dependencies / blockers

$($issue.Dependencies)
"@
    $labelArgs = @()
    foreach ($labelName in $issue.Labels) { $labelArgs += @("--label", $labelName) }
    gh issue create --repo $Repository --title $issue.Title --body $body --milestone $issue.Milestone @labelArgs | Write-Host
}

Write-Host "Bootstrap complete for ${Repository}: $($labels.Count) labels, $($milestones.Count) milestones, $($issues.Count) issue specifications."
